require 'rake'
require 'rake/gempackagetask'
require 'spec/rake/spectask'

desc "Run all specs"
Spec::Rake::SpecTask.new('spec') do |t|
  t.spec_files = FileList['spec/**/*.rb']
  t.rcov = false 
end

PKG_NAME = "sergeant_simple"
PKG_VERSION   = "1.0"
PKG_TAG = "sergeant_simple-1_0"
PKG_FILE_NAME = "#{PKG_NAME}-#{PKG_VERSION}"

spec = Gem::Specification.new do |s|
  s.name = PKG_NAME
  s.version = PKG_VERSION
  s.files = FileList['lib/**/*.rb', 'spec/**/*.rb'].to_a
  s.require_path = 'lib'
  s.test_files = Dir.glob('spec/*_spec.rb')
  s.bindir = 'bin'
  s.executables = []

  s.summary = "Battleship Player:Sergeant Simple"

  s.description = "A very simple player."
  s.author = "Micah Martin"
end

Rake::GemPackageTask.new(spec) do |pkg|
  pkg.need_zip = false
  pkg.need_tar = false
end
