require 'rake'
require 'spec/rake/spectask'
require 'rake/gempackagetask'

desc "Run all specs"
Spec::Rake::SpecTask.new('spec') do |t|
  t.spec_files = FileList['spec/**/*.rb']
  t.rcov = false
end

PKG_NAME = "battleship_tournament"
PKG_VERSION   = "1.0"
PKG_TAG = "battleship_tournament-1_0"
PKG_FILE_NAME = "#{PKG_NAME}-#{PKG_VERSION}"

spec = Gem::Specification.new do |s|
  s.name = PKG_NAME
  s.version = PKG_VERSION
  s.files = FileList['**/*'].to_a
  s.require_path = 'lib'
  s.test_files = Dir.glob('spec/*_spec.rb')
  s.bindir = 'bin'
  s.executables = ['generate_battleship_player', 'submit_battleship_player']
  s.email = "sparring-battleship@rubyforge.org"
  s.homepage = "http://sparring.rubyforge.org/"
  s.rubyforge_project = "sparring"

  s.summary = "Battleship tournament."

  s.description = "This gem provides the infrastructure needed to participate in the Battleship Tournament"
  s.author = "Micah Martin"
end

Rake::GemPackageTask.new(spec) do |pkg|
  pkg.need_zip = false
  pkg.need_tar = false
end