require 'rake'
require 'spec/rake/spectask'
require 'rake/gempackagetask'

desc "Run all specs"
Spec::Rake::SpecTask.new('spec') do |t|
  t.spec_files = FileList['spec/**/*.rb']
  t.rcov = false
end

PKG_NAME = "battleship_tournament"
PKG_VERSION   = "1.1"
PKG_FILE_NAME = "#{PKG_NAME}-#{PKG_VERSION}"

spec = Gem::Specification.new do |s|
  s.name = PKG_NAME
  s.version = PKG_VERSION
  s.files = FileList['lib/**/*', 'spec/**/*', 'bin/**/*', 'CHANGES', 'Rakefile'].to_a
  s.require_path = 'lib'
  s.test_files = Dir.glob('spec/*_spec.rb')
  s.bindir = 'bin'
  s.executables = ['generate_battleship_player', 'submit_battleship_player']
  s.email = "sparring-battleship@rubyforge.org"
  s.homepage = "http://sparring.rubyforge.org/"
  s.rubyforge_project = "sparring"
  s.summary = "Battleship tournament."
  s.description = "This gem provides the infrastructure needed to participate in the Battleship Tournament"
  s.author = "Micah Martin"

  s.add_dependency('sergeant_simple', ">= 1.0")
  s.add_dependency('rear_admiral_randy', ">= 1.0")
  s.add_dependency('alpha', ">= 1.7")
  s.add_dependency('cobra', ">= 1.0")
  s.add_dependency('commodore_cox', ">= 1.0")
  s.add_dependency('ensign_erratic', ">= 1.0.2")
  s.add_dependency('joshua_son_of_nun', ">= 1.0")
  s.add_dependency('l2p', ">= 1.0")
  s.add_dependency('sonic_death_monkey', ">= 1.0")
  s.add_dependency('ssoroka_takes_the_win', ">= 1.0")
  s.add_dependency('uss_monte_carlo', ">= 2.0.2")
  s.add_dependency('white_horseman', ">= 1.3")
end

Rake::GemPackageTask.new(spec) do |pkg|
  pkg.need_zip = false
  pkg.need_tar = false
end

task :verify_user do
  raise "RUBYFORGE_USER environment variable not set!" unless ENV['RUBYFORGE_USER']
end

task :verify_password do
  raise "RUBYFORGE_PASSWORD environment variable not set!" unless ENV['RUBYFORGE_PASSWORD']
end

task :copy_player_gems do
  system "cp ../sergeant_simple/pkg/sergeant_simple-1.0.gem pkg"
  system "cp ../rear_admiral_randy/pkg/rear_admiral_randy-1.0.gem pkg"
  system "cp submissions/*.gem pkg"
end

desc "Publish gem+tgz+zip on RubyForge. You must make sure lib/version.rb is aligned with the CHANGELOG file"
task :publish_packages => [:verify_user, :verify_password, :package, :copy_player_gems] do
  require 'meta_project'
  require 'rake/contrib/xforge'
  release_files = FileList[
    "pkg/#{PKG_FILE_NAME}.gem",
    "pkg/sergeant_simple-1.0.gem",
    "pkg/rear_admiral_randy-1.0.gem",
    "pkg/alpha-1.7.gem",
    "pkg/ensign_erratic-1.0.2.gem",
    "pkg/l2p-1.0.gem",
    "pkg/uss_monte_carlo-2.0.2.gem",
    "pkg/cobra-1.0.gem",
    "pkg/interferoman-1.2.gem",
    "pkg/sonic_death_monkey-1.0.gem",
    "pkg/white_horseman-1.3.gem",
    "pkg/commodore_cox-1.0.gem",
    "pkg/joshua_son_of_nun-1.0.gem",
    "pkg/ssoroka_takes_the_win-1.0.gem"
  ]

  Rake::XForge::Release.new(MetaProject::Project::XForge::RubyForge.new("sparring")) do |xf|
    # Never hardcode user name and password in the Rakefile!
    xf.user_name = ENV['RUBYFORGE_USER']
    xf.password = ENV['RUBYFORGE_PASSWORD']
    xf.files = release_files.to_a
    xf.release_name = "Battleship Tournament #{PKG_VERSION}"
  end
end